name: 'Post Build'
description: 'Post build comment for RNEF builds'

inputs:
  artifact-url:
    description: 'The URL of the artifact to post'
    required: true
  title:
    description: 'The title of the GitHub comment'
    required: true
  github-token:
    description: A GitHub Personal Access Token with write access to the project
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Run post build
      run: node index.js
      shell: bash
