name: 'Fingerprint'
description: 'Fingerprint the current native-related files'
inputs:
  platform:
    description: 'The platform to fingerprint: android or ios'
    required: true
  working-directory:
    description: 'The working directory to fingerprint, where the rnef.config.mjs is located'
    required: true
    default: '.'
outputs:
  hash:
    description: 'The fingerprint hash'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Run fingerprint
      run: node index.mjs
      shell: bash
