name: 'Fingerprint'
description: 'Fingerprint the current native-related files'
inputs:
  platform:
    description: 'The platform to fingerprint: android or ios'
    required: true
  working-directory:
    description: 'The working directory to fingerprint, where the rnef.config.mjs is located'
    required: true
    default: '.'
outputs:
  hash:
    description: 'The fingerprint hash'
    value: ${{ steps.fingerprint.outputs.hash }}
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run fingerprint
      id: fingerprint
      env:
        INPUT_PLATFORM: ${{ inputs.platform }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: node ${{ github.action_path }}/index.mjs
      shell: bash
